name: XCTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ios:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install any dependencies
    - name: Install Dependencies
      run: cd NavigationBackport/NavigationBackport && swift package resolve && cd ../..

    # Run tests on iPhone 16 Pro Simulator with iOS 18.0
    - name: Run Tests on iPhone 16 Pro Simulator (iOS 18.0)
      run: |
        xcodebuild test \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0'
