name: XCTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ios:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Use Swift Version 6
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0.0"

    - name: Set Xcode version 
      run: sudo xcode-select -s /Applications/Xcode_16.2.app

    # Install any dependencies
    - name: Install Dependencies
      run: cd NavigationBackport/NavigationBackport && swift package resolve && cd ../..

    # Run tests on iPhone 16 Pro Simulator with iOS 18.2
    - name: Run Tests on iPhone 16 Pro Simulator (iOS 18.2)
      run: |
        xcodebuild test \
          -scheme 'NavigationBackportApp' \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2'
